const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const H={'X-Telegram-Init-Data':tg?.initData||''};const $=x=>document.querySelector(x);
async function api(p,o={}){o.headers={...(o.headers||{}),...H,'Content-Type':'application/json'};let r=await fetch(p.startsWith('/api')?p:'/api'+p,o);let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||'Ошибка');return d}
function section(id){document.getElementById(id).scrollIntoView({behavior:'smooth'})}
function openM(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('show')}function closeM(){$('#modal').classList.remove('show')}
async function load(){try{let d=await api('/me');$('#bal').textContent='🪙 '+Number(d.user.coins).toLocaleString()+'  ⭐ '+d.user.stars;$('#profileCard').innerHTML=`<div class=avatar>${(d.user.first_name||'V')[0]}</div><b>${d.user.username?'@'+d.user.username:d.user.first_name||'Player'}</b><small>LEVEL ${d.user.level} • ${d.user.xp} XP • ⚡ ${d.user.energy}</small>`;let c=await api('/catalog');$('#caseGrid').innerHTML=c.cases.map(x=>`<button class=case onclick=caseInfo(${x.id})><img src="${x.image}"><b>${x.name}</b><small>🪙 ${x.price.toLocaleString()} • SECRET 0.1%</small></button>`).join('');$('#gameGrid').innerHTML=Object.keys(c.games).map(x=>`<button class=panel onclick=game('${x}')>◉<b>${x}</b><small>Играть • VLD + XP</small></button>`).join('');let q=await api('/quests');$('#questGrid').innerHTML=q.quests.map(x=>`<div class=quest><span>🎯 ${x.title}<small>${x.description}</small></span><button onclick=claim(${x.id}) ${x.claimed?'disabled':''}>${x.claimed?'✓':'ЗАБРАТЬ'}<br>+${x.reward} VLD</button></div>`).join('')}catch(e){openM(`<h2>VLDST</h2><p>${e.message}</p><button onclick=closeM()>OK</button>`)}}
async function caseInfo(id){let c=await api('/catalog');let x=c.cases.find(z=>z.id===id);openM(`<img class=modalimg src="${x.image}"><h2>${x.name}</h2><p>Шансы: COMMON 55% • RARE 28% • EPIC 12% • LEGENDARY 4% • MYTHIC 0.9% • SECRET 0.1%</p><button onclick=openCase(${id})>🪙 ${x.price.toLocaleString()} ОТКРЫТЬ</button>`)}
async function openCase(id){try{let d=await api('/cases/'+id+'/open',{method:'POST'});openM(`<div class=win>◈</div><h2>${d.item.name}</h2><b>${d.item.rarity}</b><p>🪙 ${d.item.value.toLocaleString()} VLD</p><button onclick=closeM();load()>ЗАБРАТЬ</button>`)}catch(e){openM(`<h2>Не получилось</h2><p>${e.message}</p><button onclick=closeM()>OK</button>`)}}
async function game(g){try{let d=await api('/games/'+g+'/play',{method:'POST'});openM(`<h2>◉ ${g}</h2><p>SCORE: ${d.score}</p><h2>+${d.reward} VLD</h2><p>+${d.xp} XP • -${d.energy} Energy</p><button onclick=closeM();load()>CONTINUE</button>`)}catch(e){openM(`<h2>GAME</h2><p>${e.message}</p><button onclick=closeM()>OK</button>`)}}
async function claim(id){try{let d=await api('/quests/'+id+'/claim',{method:'POST'});openM(`<h2>🎯 QUEST COMPLETE</h2><p>+${d.reward} VLD</p><button onclick=closeM();load()>OK</button>`)}catch(e){openM(`<h2>QUEST</h2><p>${e.message}</p><button onclick=closeM()>OK</button>`)}}
async function inventory(){let d=await api('/inventory');openM(`<h2>🎒 INVENTORY</h2>${d.items.map(x=>`<div class=row><img src="${x.image}"><span><b>${x.name}</b><small>${x.rarity} • L${x.level}</small></span><button onclick="sell(${x.inventory_id)">SELL</button></div>`).join('')||'<p>Пусто</p>'}`)}
async function sell(id){let d=await api('/inventory/'+id+'/sell',{method:'POST'});closeM();load();openM(`<h2>♻️ SOLD</h2><p>+${d.value} VLD</p><button onclick=closeM()>OK</button>`)}
async function leaderboard(){let d=await api('/leaderboard');openM('<h2>🏆 LEADERBOARD</h2>'+d.leaders.map(x=>`<div class=row><b>#${x.rank}</b><span>${x.username}<small>LV ${x.level} • ${x.xp} XP</small></span><b>${x.coins.toLocaleString()}</b></div>`).join(''))}
async function referrals(){let d=await api('/referrals');openM(`<h2>🤝 REFERRALS</h2><p>Код: <b>${d.code}</b></p><p>Приглашено: ${d.invited}</p><input value="${d.link}" readonly><button onclick=navigator.clipboard.writeText('${d.link}')>КОПИРОВАТЬ</button>`)}
async function guilds(){let d=await api('/guilds');openM(`<h2>⚔️ GUILDS</h2><button onclick=createGuild()>CREATE GUILD</button>`+d.guilds.map(x=>`<div class=row><span><b>${x.name}</b><small>LV ${x.level} • ${x.xp} XP</small></span></div>`).join(''))}
async function createGuild(){let d=await api('/guilds/create',{method:'POST'});openM(`<h2>⚔️ ${d.name}</h2><p>Гильдия создана.</p><button onclick=closeM()>OK</button>`)}
async function stars(){openM(`<h2>⭐ STAR SHOP</h2><div class=row><span>👑 Premium 7 days</span><b>100 ⭐</b></div><div class=row><span>👑 Premium 30 days</span><b>300 ⭐</b></div><div class=row><span>✨ Neon Profile</span><b>25 ⭐</b></div><p class=muted>Покупки Stars подключаются через официальный Telegram invoice flow.</p>`)}
async function daily(){try{let d=await api('/daily',{method:'POST'});openM(`<h2>🎁 DAILY</h2><p>+${d.reward} VLD</p><p>STREAK ${d.streak}</p><button onclick=closeM();load()>OK</button>`)}catch(e){openM(`<h2>DAILY</h2><p>${e.message}</p><button onclick=closeM()>OK</button>`)}}
load()
