services:
  - type: web
    name: vldst-underground
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: checksPass

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vldst-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: BOT_TOKEN
        sync: false

      - key: PUBLIC_URL
        value: https://vldst-underground.onrender.com

      - key: WEBAPP_URL
        value: https://vldst-underground.onrender.com/

      - key: ADMIN_URL
        value: https://vldst-underground.onrender.com/admin/

      - key: BOT_USERNAME
        value: VLDST_miniapp_bot

      - key: ADMIN_IDS
        sync: false

  - type: worker
    name: vldst-underground-bot
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.bot
    autoDeployTrigger: checksPass

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vldst-db
          property: connectionString

      - key: SECRET_KEY
        fromService:
          type: web
          name: vldst-underground
          envVarKey: SECRET_KEY

      - key: BOT_TOKEN
        sync: false

      - key: WEBAPP_URL
        value: https://vldst-underground.onrender.com/

databases:
  - name: vldst-db
    plan: free
