const $=s=>document.querySelector(s); let token=localStorage.getItem('vldst_admin_token')||'';
if(token) $('#t').value=token;
function auth(){token=$('#t').value.trim(); if(!token.startsWith('Bearer '))token='Bearer '+token; localStorage.setItem('vldst_admin_token',token)}
async function req(path,opt={}){auth();const r=await fetch('/api'+path,{...opt,headers:{'Content-Type':'application/json',Authorization:token,...(opt.headers||{})}});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');return d}
function out(msg,err=false){$('#status').textContent=msg;$('#status').className=err?'bad':'ok'}
async function loadAll(){try{auth();const [d,u,e]=await Promise.all([req('/admin/dashboard'),req('/admin/users'),req('/admin/economy')]);$('#dashboard').textContent=JSON.stringify(d,null,2);$('#economy').innerHTML=e.map(x=>`<div class="row"><b>${x.key}</b><input data-key="${x.key}" value="${x.value}" type="number"><button onclick="setEco('${x.key}')">SAVE</button></div>`).join('');$('#users').innerHTML=u.map(x=>`<div class="row"><span>#${x.id} ${x.nickname} · L${x.level}</span><button onclick="ban(${x.id})">${x.banned?'UNBAN':'BAN'}</button></div>`).join('');out('Connected')}catch(e){out(e.message,true)}}
async function setEco(key){try{const v=document.querySelector(`[data-key="${key}"]`).value;await req(`/admin/economy/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value:Number(v)})});out('Economy updated')}catch(e){out(e.message,true)}}
async function ban(id){try{const rows=await req('/admin/users');const u=rows.find(x=>x.id===id);await req(`/admin/users/${id}/${u?.banned?'unban':'ban'}`,{method:'POST'});loadAll()}catch(e){out(e.message,true)}}
$('#quest').onsubmit=async e=>{e.preventDefault();try{const o=Object.fromEntries(new FormData(e.target));['target','reward_vld','reward_xp'].forEach(k=>o[k]=Number(o[k]));await req('/admin/quests',{method:'POST',body:JSON.stringify(o)});e.target.reset();out('Quest created')}catch(x){out(x.message,true)}};
$('#case').onsubmit=async e=>{e.preventDefault();try{const o=Object.fromEntries(new FormData(e.target));o.price=Number(o.price);o.weights=JSON.parse(o.weights);await req('/admin/cases',{method:'POST',body:JSON.stringify(o)});e.target.reset();out('Case created')}catch(x){out(x.message,true)}};
$('#broadcast').onsubmit=async e=>{e.preventDefault();try{const o=Object.fromEntries(new FormData(e.target));await req('/admin/broadcast',{method:'POST',body:JSON.stringify(o)});e.target.reset();out('Broadcast queued')}catch(x){out(x.message,true)}};
async function boot(){if(token)await loadAll()} boot();
